### ISSUE TITLE
tabelline

### ISSUE THREAD

**Issue by FabioZTessitore** [christian99salerno/iterazione_c#1]
la definizione delle variabili ... va fatta all'inizio, non nei cicli

**Comment by christian99salerno** [comment]
va bene

**Comment by christian99salerno** [comment]
professore sul mio computer mi stampa solo la tabellina dell'uno

**Comment by FabioZTessitore** [comment]
così gli hai detto di fare. Prova a stampare i valori di `i` e `j` e vedi cosa esce

**Comment by christian99salerno** [comment]
l'ho fatto e i rimane uguale a 1 e j = 1 2 3 4 5 6 7 8 9 10

**Comment by FabioZTessitore** [comment]
Stampa i nel ciclo esterno e j in quello interno

Il 30 mag 2017 4:48 PM, "christian99salerno" <notifications@github.com> ha
scritto:

**Comment by christian99salerno** [comment]
entrambe vanno da 1 a 11

**Comment by FabioZTessitore** [comment]
Ma non è vero. Se fosse così stamperebbe tutte le tabelline

Il 30 mag 2017 4:51 PM, "christian99salerno" <notifications@github.com> ha
scritto:

**Comment by christian99salerno** [comment]
questo mi è uscito

**Comment by christian99salerno** [comment]
e a scuola stampava bene

**Comment by christian99salerno** [comment]
controllate email ci dovrebbero essere due foto

**Comment by FabioZTessitore** [comment]
Se nelle stampe non scrivi chi stai stampando, come fai a sapere chi è i e
chi è j?

Il 30 mag 2017 5:00 PM, "christian99salerno" <notifications@github.com> ha
scritto:

**Comment by christian99salerno** [comment]
j:1
j:2
j:3
j:4
j:5
j:6
j:7
j:8
j:9
j:10
i:1
i:2
i:3
i:4
i:5
i:6
i:7
i:8
i:9
i:10

**Comment by FabioZTessitore** [comment]
Lo vedi?

Il 30 mag 2017 5:03 PM, "christian99salerno" <notifications@github.com> ha
scritto:

**Comment by christian99salerno** [comment]
cosa ? stampano da 1 a 10

**Comment by christian99salerno** [comment]
e si trova non dovrebbero fare così

**Comment by FabioZTessitore** [comment]
Prova ad immaginare come dovrebbero uscire quei numeri

Il 30 mag 2017 5:05 PM, "christian99salerno" <notifications@github.com> ha
scritto:

**Comment by christian99salerno** [comment]
1*1=1 ....  1*10= 10
2..
3..
4..
5...
6...
7..
8...
9..
10..            10*10=100

**Comment by FabioZTessitore** [comment]
Si, ma i e j non vengono così. Cosa manca?

Il 30 mag 2017 5:13 PM, "christian99salerno" <notifications@github.com> ha
scritto:

**Comment by christian99salerno** [comment]
i deve rimanere ferma fino a quando j non arriva a 10 e poi i va al valore successivo e così anche per il valore che assume deve essere fermo fino a che j non ritorna a 10 fino a che i non ritorna a 10

**Comment by christian99salerno** [comment]
aaa ho capito j quando arriva a 10 dopo deve ritornare a 1

**Comment by FabioZTessitore** [comment]
Però non succede, quale parte manca?

Il 30 mag 2017 5:18 PM, "christian99salerno" <notifications@github.com> ha
scritto:

**Comment by christian99salerno** [comment]
while (i<=10){
j=1;
while ...

**Comment by FabioZTessitore** [comment]
Ok

Il 30 mag 2017 5:19 PM, "Fabio Z Tessitore" <fabioztessitore@gmail.com> ha
scritto:

Però non succede, quale parte manca?

Il 30 mag 2017 5:18 PM, "christian99salerno" <notifications@github.com> ha
scritto:

**Comment by christian99salerno** [comment]
era questo che mancava e basta giusto?
