### ISSUE TITLE
sumvet

### ISSUE THREAD

**Issue by FabioZTessitore** [christian99salerno/iterazione_c#10]
- [ ] c'è un errore gravissimo di accesso alla memoria (che poi si traduce nella distruzione dello stack)
- [ ] la soluzione calcolata non è corretta (con i dati dell'esempio la media deve essere 4.2)

**Comment by FabioZTessitore** [comment]
C'è da correggere il problema di accesso alla memoria. Controlla gli indici

**Comment by christian99salerno** [comment]
gli indici sono ok qual è il problema?

**Comment by FabioZTessitore** [comment]
Evidentemente no

**Comment by christian99salerno** [comment]
che intendete con indice

**Comment by FabioZTessitore** [comment]
Quello che intendono tutti

**Comment by christian99salerno** [comment]
ah... date sempre tutto per scontato

**Comment by christian99salerno** [comment]
io intento l'indice "i"

**Comment by FabioZTessitore** [comment]
Anche io

**Comment by christian99salerno** [comment]
e va bene ho controllato lo stampa anche ed è corretto o sono io cieco

**Comment by FabioZTessitore** [comment]
Allora bisogna concludere che non sai come si usano i vettori

**Comment by christian99salerno** [comment]
scusate il vettore riempie seguendo l'indice

**Comment by christian99salerno** [comment]
che a ogni ciclo viene aumentato fino al massimo di 10

**Comment by FabioZTessitore** [comment]
Appunto, non sai usare i vettori

**Comment by christian99salerno** [comment]
... ok

**Comment by christian99salerno** [comment]
allora mi spiegate come si usano

**Comment by christian99salerno** [comment]
prof. ma l'errore sta nello scanf quando assegno al vettore i suoi elementi?

**Comment by FabioZTessitore** [comment]
C'è lo stesso errore ogni volta che usi il vettore.
Fatti stampare l'indice i e vedi quali stampa prima di esplodere

**Comment by christian99salerno** [comment]
l'ho fatto e non esplode, esplode alla fine con quell'errore, al termine del programma

**Comment by christian99salerno** [comment]
dopo che ha stampato la media

**Comment by FabioZTessitore** [comment]
Vabbè mi arrendo.
Se hai un vettore di 10 elementi, gli elementi hanno indice da 0 a 9

**Comment by FabioZTessitore** [comment]
in attesa

**Comment by christian99salerno** [comment]
ah ho capito


Il giorno lun 11 feb 2019 alle ore 11:21 Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
ora va bene.
ancora meglio sarebbe stato `for (i=0; i<10; i++)`

Dopo aver letto questa questa issue, chiudila. Grazie
