### ISSUE TITLE
quadrato

### ISSUE THREAD

**Issue by FabioZTessitore** [christian99salerno/iterazione_c#2]
quando si usa un solo carattere prendi l'abitudine di usare `int` e non `char`.
(in ogni caso non era richiesto far scegliere il carattere da usare, doveva essere asterisco)

**Comment by christian99salerno** [comment]
ah quindi cosa devo modificare devo mettere un carattere predefinito? e devo usare int o posso lasciar stare queste cose?

**Comment by FabioZTessitore** [comment]
Per quanto mi riguarda puoi togliere quelle cose e stampare asterisco. Se
però le vuoi tenere, la variabile deve essere int

Il 1 giu 2017 5:36 PM, "christian99salerno" <notifications@github.com> ha
scritto:

**Comment by christian99salerno** [comment]
va bene

**Comment by christian99salerno** [comment]
aggiustato
