### ISSUE TITLE
binario

### ISSUE THREAD

**Issue by FabioZTessitore** [christian99salerno/iterazione_c#5]

**Comment by christian99salerno** [comment]
Che vuol dire nessuna descrizione data?

**Comment by FabioZTessitore** [comment]
Niente, ho aperto la issue senza scrivere niente

**Comment by christian99salerno** [comment]
A ok già sapete che sbaglierò :)

**Comment by FabioZTessitore** [comment]
Si si si ha ha

Il 10 giu 2017 8:12 PM, "christian99salerno" <notifications@github.com> ha
scritto:

**Comment by christian99salerno** [comment]
Ne sono sicuro anche io :)

**Comment by FabioZTessitore** [comment]
Prova a non usare la funzione pow

**Comment by FabioZTessitore** [comment]
questo ancora non va bene

**Comment by christian99salerno** [comment]
bhè perchè non riesco ad andare avanti o meglio a ritoccarlo e ad aggiungere la condizione

**Comment by FabioZTessitore** [comment]
1. eliminare la funzione `pow()` [pensa a cosa ti dà come risultato e a cosa significa quel numero nel tuo calcolo]
2. controllo dell'input [quando è valido il numero dato in ingresso? quando non lo è?]

**Comment by FabioZTessitore** [comment]
per quanto riguarda la condizione, cerca di rispondere alla domanda: quando il numero inserito è un numero binario valido? quando non lo è?

**Comment by FabioZTessitore** [comment]
niente?

**Comment by christian99salerno** [comment]
Mi sto spremendo le meningi ma ho pensato solo a scomperre il numero in cifre e paragonarle a 0 o 1 per vedere se è binario ma per fare ciò avrei bisogno di un altro ciclo while all'interno del do while

**Comment by FabioZTessitore** [comment]
Bravo, metti in pratica quello che hai scritto

**Comment by christian99salerno** [comment]
controllate se la mia idea geniale con i contatori è giusta perché a me lo sembra e ciò messo un po' per arrivarci. perché sapevo la condizione ma non sapevo cosa doveva fare se era soddisfatta o meno.
Ho avuto poi questa idea abbastanza banale

**Comment by christian99salerno** [comment]
E' gianale perche' e' banale

**Comment by christian99salerno** [comment]
praticamente ho pensato di contare il numero delle cifre uguali a 1 e 0 e confrontarlo con il numero delle cifre che hai il numero stesso così se sono uguali i 2 contatori vuol dire che è binario altrimenti decimale

**Comment by FabioZTessitore** [comment]
geniaccio. Solo per curiosità vatti a vedere la mia soluzione perché è diversa.
