### ISSUE TITLE
cripta

### ISSUE THREAD

**Issue by FabioZTessitore** [christian99salerno/iterazione_c#6]
1. i numeri fino a 1000 non ti piacciono?
2. l'algoritmo è corretto, ma risulta poco chiaro che estrai le cifre e poi le trasformi. Prova a riscrivere separando queste operazioni
3. La ricostruzione del numero di output è corretta ma anche qui poco chiaro a chi legge come vengono riordinate le cifre trasformate

**Comment by christian99salerno** [comment]
va bene proverò ad aggiustare

**Comment by christian99salerno** [comment]
voi avete detto di inserire un numero di 4 cifre in  che senso i numeri fino a 1000 non ti piacciono?

**Comment by FabioZTessitore** [comment]
se inserisco il numero 3 lo posso interpretare come 0003 (quattro cifre)

**Comment by christian99salerno** [comment]
le cose si complicano allora

**Comment by FabioZTessitore** [comment]
no perché sai che sono sempre 4 cifre

**Comment by christian99salerno** [comment]
faccio prima i punti che mi avete segnato 1 e 2 e poi ritorno su questo

**Comment by christian99salerno** [comment]
ho risolto adesso me l'ha caricato su github la nuova versione penso di aver soddisfatto il punto 2 ma come potrei se controllate il nuovo file caricato rendere più chiaro il nuovo ordine delle cifre?

**Comment by FabioZTessitore** [comment]
l'ordine delle cifre iniziali è chiaro `abcd`. Quello delle cifre finali no

**Comment by christian99salerno** [comment]
controllate adesso

**Comment by FabioZTessitore** [comment]
perché usi due variabili t1 e t2? una non ti bastava? [in ogni caso si poteva forse evitare]

il problema con la ricostruzione del numero sta nel fatto che scrivi due linee rendendo abbastanza oscuro il risultato. O ne fai solo una oppure spezza i vari passaggi

**Comment by christian99salerno** [comment]
va bene

**Comment by christian99salerno** [comment]
vedete adesso

**Comment by FabioZTessitore** [comment]
ok, adesso includi anche i numeri più piccoli di 1000

**Comment by christian99salerno** [comment]
va bene

**Comment by christian99salerno** [comment]
ora dovrebbe andare bene

**Comment by FabioZTessitore** [comment]
dovrebbe funzionare, ma si prende pure i numeri negativi haha

ps. cancella il file binario cripta e se necessario aggiusta decripta.c in base a quello che ci siamo detti finora

**Comment by christian99salerno** [comment]
ok escludo i negativi ci provo e perchè dovrei cancellare il file binario cripta?
in che senso binario cripta?
e si decripta devo aggiustarlo perché è un disastro poichè pensavo che era facile farlo sulla falsa riga di cripta

**Comment by christian99salerno** [comment]
numeri negativi esclusi

**Comment by FabioZTessitore** [comment]
file binario significa l'eseguibile (per sbaglio lo hai caricato)
