### ISSUE TITLE
decripta

### ISSUE THREAD

**Issue by FabioZTessitore** [christian99salerno/iterazione_c#7]
in attesa

**Comment by christian99salerno** [comment]
ho problemi nel farmi restituire le cifre originali

**Comment by FabioZTessitore** [comment]
Comincia ad aggiustare le cose che abbiamo detto in cripta.c

Per quanto riguarda le cifre, il problema è proprio trovare l'algoritmo giusto

**Comment by christian99salerno** [comment]
il mio decripta è la copia dell'attuale cripta ho preso carta e penna e sto impazzendo per tornare al numero originale

**Comment by christian99salerno** [comment]
potete controllare se va bene decripta
