### ISSUE TITLE
pi greco

### ISSUE THREAD

**Issue by FabioZTessitore** [christian99salerno/iterazione_c#9]
cerchiamo di togliere l'if dal ciclo

**Comment by FabioZTessitore** [comment]
cerchiamo di togliere l'if dal ciclo

**Comment by christian99salerno** [comment]
ok adesso vedo

**Comment by FabioZTessitore** [comment]
ok, adesso proviamo ad eliminare la moltiplicazione (è troppo costosa)

**Comment by christian99salerno** [comment]
Whatttttttt......................................................................................................................whatttttttttttttttttttttttttttttttttttttttttt..............................whatttttttttttttttttttttttttt................

**Comment by christian99salerno** [comment]
why...why...why...alone why?
